[settings]
pipx.uvx = true

[tools]
"aqua:rust-lang/rustup" = "latest"
bun = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-tarpaulin" = "latest"
"pipx:bakefile" = "latest"
"pipx:toml-sort" = "latest"
"pipx:zerv-version" = "latest"
pre-commit = "latest"
uv = "latest"
