[settings]
pipx.uvx = true

[tools]
bun = "latest"
"cargo:cargo-audit" = "latest" # add this to bakefile // cargo-audit
"cargo:cargo-tarpaulin" = "latest" # add this to bakefile // cargo-tarpaulin
"pipx:bakefile" = "latest"
"pipx:toml-sort" = "latest"
"pipx:zerv-version" = "latest"
pre-commit = "latest"
rust = "latest" # "aqua:rust-lang/rustup" = "latest"
uv = "latest"
