name: pre-commit

on:
    workflow_call:
        inputs:
            python_version:
                required: false
                type: string
                default: "3.14"

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: setup-uv
              uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
              with:
                  version: "latest"
                  enable-cache: true
                  cache-python: true
                  python-version: ${{ inputs.python_version }}

            - name: cache-deps
              env:
                  CACHE_KEY_PREFIX: deps-${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-py${{ inputs.python_version }}
                  CACHE_KEY_DEPS: ${{ hashFiles('uv.lock') }}
              uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
              with:
                  path: |
                      ${{ github.workspace }}/.venv
                      ~/.cache/pre-commit
                      ~/.cache/ruff
                      ~/.bun/install/cache
                      ${{ github.workspace }}/target/
                  key: ${{ env.CACHE_KEY_PREFIX }}-${{ env.CACHE_KEY_DEPS }}-${{ github.run_id }}-${{ github.run_attempt }}
                  restore-keys: |
                      ${{ env.CACHE_KEY_PREFIX }}-${{ env.CACHE_KEY_DEPS }}-${{ github.run_id }}-
                      ${{ env.CACHE_KEY_PREFIX }}-${{ env.CACHE_KEY_DEPS }}-
                      ${{ env.CACHE_KEY_PREFIX }}-

            - name: install-dependencies
              run: uv sync --all-extras --all-groups --frozen

            - name: setup-path
              run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

            - name: setup-bun
              uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
              with:
                  bun-version: latest

            - name: setup-rust-toolchain
              uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # stable
              with:
                  toolchain: nightly
                  components: rustfmt, clippy

            - name: run-pre-commit
              run: uv run pre-commit run --all-files
