name: publish-python-package

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
                description: "PEP440 version string"
            registry:
                required: false
                type: string
                description: "Publish index (pypi or testpypi)"
                default: "testpypi"
            python_version:
                required: false
                type: string
                description: "Python version"
        secrets:
            PYPI_API_TOKEN:
                required: true

jobs:
    publish-pypi:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                    - os: macos-latest
                      target: aarch64-apple-darwin
                    - os: macos-latest
                      target: x86_64-apple-darwin
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                    - os: windows-latest
                      target: aarch64-pc-windows-msvc

        steps:
            - name: checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: setup-uv
              uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
              with:
                  python-version: ${{ inputs.python_version }}
                  version: "latest"
                  enable-cache: true

            - name: cache-publish
              uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      ${{ github.workspace }}/target/
                      ${{ github.workspace }}/.venv
                  key: publish-${{ github.job }}-${{ runner.os }}-${{ matrix.target }}

            - name: install-bake
              run: |
                  uv tool install "bakefile[lib]"
                  uv tool upgrade --all
                  bake --version

            - name: setup-rust-toolchain
              uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # stable
              with:
                  toolchain: stable
                  targets: ${{ matrix.target }}

            - name: install-cross-compilation-dependencies
              if: matrix.target == 'aarch64-unknown-linux-gnu'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gcc-aarch64-linux-gnu
                  echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

            # TODO:
            - name: install-dependencies
              run: uv sync --all-extras --all-groups --frozen

            - name: setup-path
              run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

            - name: publish
              shell: bash
              run: |
                  BAKE_PUBLISH_TOKEN=${{ secrets.PYPI_API_TOKEN }} \
                  bake publish \
                      --registry "${{ inputs.registry }}" \
                      --version "${{ inputs.version }}" \
                      --target "${{ matrix.target }}"
