name: publish-crates

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
            python_version:
                required: false
                type: string
                description: "Python version"
        secrets:
            # pass token in empty string will be in dry-run mode
            CRATES_API_TOKEN:
                required: true

jobs:
    release-crates:
        name: release-crates
        runs-on: ubuntu-latest
        steps:
            - name: checkout-repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: setup-uv
              uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
              with:
                  python-version: ${{ inputs.python_version }}
                  version: "latest"
                  enable-cache: true

            - name: install-bake
              run: |
                  uv tool install "bakefile[lib]"
                  uv tool upgrade --all
                  bake --version

            - name: setup-rust-toolchain
              uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # stable
              with:
                  toolchain: stable

            - name: publish
              run: |
                  BAKE_PUBLISH_TOKEN=${{ secrets.CRATES_API_TOKEN }} \
                  bake publish \
                      --registry crates \
                      --version "${{ inputs.version }}"
