name: publish-crates

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
        secrets:
            # pass token in empty string will be in dry-run mode
            CRATES_API_TOKEN:
                required: true

jobs:
    publish-crates:
        name: publish-crates
        runs-on: ubuntu-latest
        steps:
            - name: checkout-repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: setup-mise
              uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
              # env:
              #    MISE_JOBS: 1

            - name: cache-publish
              env:
                  CACHE_KEY_PREFIX: publish-${{ github.workflow }}-${{ github.job }}-${{ runner.os }}
              uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      ~/.local/share/uv
                      ~/.cache/uv
                      ${{ github.workspace }}/target/
                      ${{ github.workspace }}/.venv
                  key: ${{ env.CACHE_KEY_PREFIX }}-${{ github.run_id }}-${{ github.run_attempt }}
                  restore-keys: |
                      ${{ env.CACHE_KEY_PREFIX }}-${{ github.run_id }}-
                      ${{ env.CACHE_KEY_PREFIX }}-

            - name: install-dependencies
              shell: bash
              run: |
                  uv sync --all-extras --all-groups --frozen
                  echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

            - name: publish
              run: |
                  BAKE_PUBLISH_TOKEN=${{ secrets.CRATES_API_TOKEN }} \
                  bake publish \
                      --registry crates \
                      --version "${{ inputs.version }}"
